apiVersion: apps/v1
kind: Deployment
metadata:
  name: tandembrain-app
  namespace: tandembrain
  labels:
    app: tandembrain
    component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tandembrain
      component: app
  template:
    metadata:
      labels:
        app: tandembrain
        component: app
    spec:
      serviceAccountName: tandembrain-app
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
        args:
          - "--port=5432"
          - "--structured-logs"
          - "neuronotify:us-west2:tandembrain-db"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
      - name: tandembrain-app
        image: us-west2-docker.pkg.dev/neuronotify/tandembrain/tandembrain-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: tandembrain-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: tandembrain-config
              key: PORT
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              name: tandembrain-config
              key: GOOGLE_CLOUD_PROJECT
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: tandembrain-config
              key: FIREBASE_PROJECT_ID
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tandembrain-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: tandembrain-secrets
              key: JWT_SECRET
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: tandembrain-secrets
              key: ANTHROPIC_API_KEY
        - name: VITE_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: tandembrain-secrets
              key: VITE_FIREBASE_API_KEY
        - name: VITE_FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: tandembrain-secrets
              key: VITE_FIREBASE_AUTH_DOMAIN
        - name: VITE_FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: tandembrain-secrets
              key: VITE_FIREBASE_PROJECT_ID
        - name: VITE_FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: tandembrain-secrets
              key: VITE_FIREBASE_STORAGE_BUCKET
        - name: VITE_FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: tandembrain-secrets
              key: VITE_FIREBASE_MESSAGING_SENDER_ID
        - name: VITE_FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: tandembrain-secrets
              key: VITE_FIREBASE_APP_ID
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5