apiVersion: v1
kind: ServiceAccount
metadata:
  name: tandembrain-app
  namespace: tandembrain
  annotations:
    iam.gke.io/gcp-service-account: tandembrain-app@neuronotify.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tandembrain-agent
  namespace: tandembrain
  annotations:
    iam.gke.io/gcp-service-account: tandembrain-agent@neuronotify.iam.gserviceaccount.com